# Generated by Django 4.2.8 on 2025-12-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_type',
            field=models.CharField(choices=[('rfq', 'RFQ (Request for Quotation)'), ('production', 'Production PO')], default='rfq', help_text='RFQ allows pre_estimate/confirmed/locked; Production requires confirmed/locked only', max_length=20),
        ),
    ]
