# Generated by Django 4.2.8 on 2026-01-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("procurement", "0002_purchaseorder_po_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseorder",
            unique_together={("organization", "po_number")},
        ),
    ]
