# Generated by Django 4.2.8 on 2026-01-10 06:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_saas_ready_fields"),
        ("procurement", "0003_fix_unique_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "article_no",
                    models.CharField(
                        db_index=True,
                        help_text="Supplier article number (unique per supplier)",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Material name in English", max_length=200
                    ),
                ),
                (
                    "name_zh",
                    models.CharField(
                        blank=True, help_text="Material name in Chinese", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fabric", "Fabric"),
                            ("trim", "Trim"),
                            ("label", "Label"),
                            ("packaging", "Packaging"),
                        ],
                        max_length=50,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=100)),
                ("color_code", models.CharField(blank=True, max_length=50)),
                (
                    "composition",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 80% Nylon, 20% Spandex",
                        max_length=200,
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True, help_text="e.g., 180 GSM", max_length=50
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        blank=True, help_text="e.g., 150 cm", max_length=50
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="yards",
                        help_text="Standard unit: yards, meters, pcs, etc.",
                        max_length=20,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Standard unit price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code: USD, TWD, CNY, etc.",
                        max_length=3,
                    ),
                ),
                (
                    "moq",
                    models.IntegerField(
                        blank=True, help_text="Minimum Order Quantity", null=True
                    ),
                ),
                (
                    "lead_time_days",
                    models.IntegerField(
                        blank=True, help_text="Standard lead time in days", null=True
                    ),
                ),
                (
                    "wastage_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Standard wastage percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="core.organization",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="procurement.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materials",
                "db_table": "materials",
                "ordering": ["name"],
                "unique_together": {("organization", "supplier", "article_no")},
            },
        ),
    ]
