# Generated by Django 4.2.8 on 2026-01-10 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0004_add_material_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="poline",
            name="material",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to Material master data",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="po_lines",
                to="procurement.material",
            ),
        ),
    ]
