# Generated by Django 4.2.8 on 2026-01-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0005_add_material_to_poline"),
    ]

    operations = [
        migrations.AddField(
            model_name="poline",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poline",
            name="is_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this line has been reviewed and confirmed",
            ),
        ),
        migrations.AddField(
            model_name="poline",
            name="notes",
            field=models.TextField(blank=True, help_text="Line item notes"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("ready", "Ready to Send"),
                    ("sent", "Sent"),
                    ("confirmed", "Confirmed"),
                    ("partial_received", "Partial Received"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
