# Generated by Django 4.2.8 on 2026-01-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0006_add_poline_confirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="poline",
            name="actual_delivery",
            field=models.DateField(blank=True, help_text="實際交貨日期", null=True),
        ),
        migrations.AddField(
            model_name="poline",
            name="delivery_notes",
            field=models.TextField(blank=True, help_text="交期追蹤備註"),
        ),
        migrations.AddField(
            model_name="poline",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("shipped", "Shipped"),
                    ("partial", "Partial"),
                    ("received", "Received"),
                    ("delayed", "Delayed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="poline",
            name="expected_delivery",
            field=models.DateField(blank=True, help_text="供應商預計交期", null=True),
        ),
        migrations.AddField(
            model_name="poline",
            name="required_date",
            field=models.DateField(
                blank=True, help_text="物料需求日期（生產需要的最晚時間）", null=True
            ),
        ),
    ]
