# Generated by Django 4.2.8 on 2026-01-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0007_add_poline_delivery_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="sent_at",
            field=models.DateTimeField(blank=True, help_text="Email 發送時間", null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="sent_count",
            field=models.IntegerField(default=0, help_text="發送次數"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="sent_to_email",
            field=models.EmailField(blank=True, help_text="發送目標 Email", max_length=254),
        ),
    ]
