# Generated by Django 4.2.8 on 2026-01-21 10:00
# P23: Add in_production and shipped status to PurchaseOrder

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0008_add_po_email_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("ready", "Ready to Send"),
                    ("sent", "Sent"),
                    ("confirmed", "Confirmed"),
                    ("in_production", "In Production"),
                    ("shipped", "Shipped"),
                    ("partial_received", "Partial Received"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
