# Generated by Django 4.2.8 on 2026-01-02 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("transition", "Status Transition"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("export", "Export"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model class name, e.g., 'SampleRun', 'BOMItem'",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        blank=True, help_text="UUID of the affected object", null=True
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of the object",
                        max_length=255,
                    ),
                ),
                (
                    "old_data",
                    models.JSONField(
                        blank=True, help_text="State before the change", null=True
                    ),
                ),
                (
                    "new_data",
                    models.JSONField(
                        blank=True, help_text="State after the change", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "request_id",
                    models.CharField(
                        blank=True, help_text="Request ID for tracing", max_length=100
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, help_text="Additional context data", null=True
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="audit_logs_organiz_af0d8d_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="audit_logs_model_n_656046_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="audit_logs_user_id_fbfd51_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_logs_action_391715_idx",
                    ),
                ],
            },
        ),
    ]
