# Generated by Django 4.2.8 on 2026-01-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("manufacturing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturingworkorder",
            name="mwo_number",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="manufacturingworkorder",
            unique_together={("organization", "mwo_number")},
        ),
    ]
