# Generated by Django 4.2.8 on 2026-01-10 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0011_add_measurement_point_name_zh"),
        ("costing", "0007_alter_usagescenario_purpose"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_saas_ready_fields"),
        ("procurement", "0005_add_material_to_poline"),
        ("orders", "0002_fix_unique_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        db_index=True, help_text="Customer PO number", max_length=50
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        help_text="Internal production order number",
                        max_length=50,
                    ),
                ),
                ("customer", models.CharField(max_length=200)),
                (
                    "customer_po_ref",
                    models.CharField(
                        blank=True, help_text="Customer PO reference", max_length=100
                    ),
                ),
                (
                    "total_quantity",
                    models.IntegerField(help_text="Total order quantity"),
                ),
                (
                    "size_breakdown",
                    models.JSONField(
                        help_text='{"XS": 100, "S": 200, "M": 300, "L": 200, "XL": 100}'
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Agreed FOB price per unit",
                        max_digits=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Total order amount", max_digits=12
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("materials_ordered", "Materials Ordered"),
                            ("in_production", "In Production"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("order_date", models.DateField()),
                ("delivery_date", models.DateField(help_text="Target delivery date")),
                ("actual_delivery", models.DateField(blank=True, null=True)),
                (
                    "mrp_calculated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether material requirements have been calculated",
                    ),
                ),
                ("mrp_calculated_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bulk_costing",
                    models.ForeignKey(
                        blank=True,
                        help_text="Confirmed bulk costing for this order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_orders",
                        to="costing.costsheetversion",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_orders",
                        to="core.organization",
                    ),
                ),
                (
                    "style_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders",
                        to="styles.stylerevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Order",
                "verbose_name_plural": "Production Orders",
                "db_table": "production_orders",
                "ordering": ["-created_at"],
                "unique_together": {("organization", "order_number")},
            },
        ),
        migrations.CreateModel(
            name="MaterialRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("material_name", models.CharField(max_length=255)),
                ("material_name_zh", models.CharField(blank=True, max_length=255)),
                ("category", models.CharField(max_length=50)),
                ("supplier", models.CharField(blank=True, max_length=255)),
                ("supplier_article_no", models.CharField(blank=True, max_length=100)),
                ("unit", models.CharField(max_length=20)),
                (
                    "consumption_per_piece",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Consumption per garment",
                        max_digits=10,
                    ),
                ),
                (
                    "wastage_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Wastage percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "order_quantity",
                    models.IntegerField(
                        help_text="Order quantity (from ProductionOrder)"
                    ),
                ),
                (
                    "gross_requirement",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="order_qty × consumption",
                        max_digits=12,
                    ),
                ),
                (
                    "wastage_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="gross_requirement × wastage%",
                        max_digits=12,
                    ),
                ),
                (
                    "total_requirement",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="gross_requirement + wastage_quantity",
                        max_digits=12,
                    ),
                ),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Current inventory (if tracked)",
                        max_digits=12,
                    ),
                ),
                (
                    "order_quantity_needed",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="total_requirement - current_stock (if positive)",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("calculated", "Calculated"),
                            ("ordered", "Ordered"),
                            ("received", "Received"),
                        ],
                        default="calculated",
                        max_length=20,
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bom_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_requirements",
                        to="styles.bomitem",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_requirements",
                        to="orders.productionorder",
                    ),
                ),
                (
                    "purchase_order_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="Generated PO line for this requirement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_requirements",
                        to="procurement.poline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Requirement",
                "verbose_name_plural": "Material Requirements",
                "db_table": "material_requirements",
                "ordering": ["category", "material_name"],
                "unique_together": {("production_order", "bom_item")},
            },
        ),
    ]
