# Generated by Django 4.2.8 on 2026-01-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_add_production_order_and_material_requirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequirement",
            name="expected_delivery",
            field=models.DateField(
                blank=True, help_text="預計交期（從供應商 lead time 計算）", null=True
            ),
        ),
        migrations.AddField(
            model_name="materialrequirement",
            name="is_reviewed",
            field=models.BooleanField(
                default=False, help_text="Whether this requirement has been reviewed"
            ),
        ),
        migrations.AddField(
            model_name="materialrequirement",
            name="required_date",
            field=models.DateField(blank=True, help_text="物料需求日期（生產需要的時間）", null=True),
        ),
        migrations.AddField(
            model_name="materialrequirement",
            name="review_notes",
            field=models.TextField(blank=True, help_text="Notes from review process"),
        ),
        migrations.AddField(
            model_name="materialrequirement",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materialrequirement",
            name="reviewed_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Adjusted quantity after review (if different from calculated)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="materialrequirement",
            name="reviewed_unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Confirmed unit price for this material",
                max_digits=10,
                null=True,
            ),
        ),
    ]
