# Generated by Django 4.2.8 on 2026-01-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("samples", "0011_add_related_names_for_tracking"),
        ("orders", "0004_add_mr_review_and_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="approved_sample_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The Sample Run (typically Size Set) that was approved before bulk production",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_orders",
                to="samples.samplerun",
            ),
        ),
    ]
