# Generated by Django 4.2.8 on 2025-12-19 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('style_number', models.CharField(db_index=True, help_text='e.g., LW1FLPS', max_length=50)),
                ('style_name', models.CharField(help_text='e.g., Nulu Cami Tank', max_length=200)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('customer', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_styles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
                'db_table': 'styles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StyleRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_label', models.CharField(help_text='e.g., Rev A, Rev B, PP', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_production', 'In Production'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changes_from_previous', models.JSONField(blank=True, help_text='AI-detected changes from previous revision', null=True)),
                ('draft_bom_data', models.JSONField(blank=True, help_text='AI-extracted BOM data (draft, pending review)', null=True)),
                ('draft_measurement_data', models.JSONField(blank=True, help_text='AI-extracted measurement data (draft, pending review)', null=True)),
                ('draft_construction_data', models.JSONField(blank=True, help_text='AI-extracted construction data (draft, pending review)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_revisions', to=settings.AUTH_USER_MODEL)),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_revisions', to='styles.stylerevision')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='styles.style')),
            ],
            options={
                'verbose_name': 'Style Revision',
                'verbose_name_plural': 'Style Revisions',
                'db_table': 'style_revisions',
                'ordering': ['-created_at'],
                'unique_together': {('style', 'revision_label')},
            },
        ),
        migrations.AddField(
            model_name='style',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='styles.stylerevision'),
        ),
        migrations.AddField(
            model_name='style',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='core.organization'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point_name', models.CharField(max_length=100)),
                ('point_code', models.CharField(blank=True, max_length=20)),
                ('values', models.JSONField()),
                ('tolerance_plus', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('tolerance_minus', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('unit', models.CharField(default='cm', max_length=10)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='styles.stylerevision')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'db_table': 'measurements',
                'ordering': ['point_name'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('description', models.TextField()),
                ('stitch_type', models.CharField(blank=True, max_length=50)),
                ('machine_type', models.CharField(blank=True, max_length=100)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_steps', to='styles.stylerevision')),
            ],
            options={
                'verbose_name': 'Construction Step',
                'verbose_name_plural': 'Construction Steps',
                'db_table': 'construction_steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_number', models.IntegerField()),
                ('category', models.CharField(choices=[('fabric', 'Fabric'), ('trim', 'Trim'), ('label', 'Label'), ('packaging', 'Packaging')], max_length=50)),
                ('material_name', models.CharField(max_length=200)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('color_code', models.CharField(blank=True, max_length=50)),
                ('consumption', models.DecimalField(blank=True, decimal_places=4, help_text='Consumption per piece', max_digits=10, null=True)),
                ('consumption_maturity', models.CharField(choices=[('unknown', 'Unknown'), ('pre_estimate', 'Pre-Estimate'), ('confirmed', 'Confirmed'), ('locked', 'Locked')], default='unknown', max_length=20)),
                ('unit', models.CharField(help_text='e.g., yards, meters, pcs', max_length=20)),
                ('placement', models.JSONField(blank=True, default=list, help_text="List of placements, e.g., ['body', 'sleeve']")),
                ('wastage_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Wastage percentage', max_digits=5)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='styles.stylerevision')),
            ],
            options={
                'verbose_name': 'BOM Item',
                'verbose_name_plural': 'BOM Items',
                'db_table': 'bom_items',
                'ordering': ['item_number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='style',
            unique_together={('organization', 'style_number')},
        ),
    ]
