# Generated by Django 4.2.8 on 2025-12-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='supplier_article_no',
            field=models.CharField(blank=True, help_text="Supplier's article/material number (key for procurement)", max_length=100),
        ),
    ]
