# Generated by Django 4.2.8 on 2025-12-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0002_bomitem_supplier_article_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='leadtime_days',
            field=models.IntegerField(blank=True, help_text='Total lead time in days', null=True),
        ),
    ]
