# Generated by Django 4.2.8 on 2025-12-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0003_add_leadtime_to_bomitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='material_status',
            field=models.CharField(blank=True, help_text='e.g., Approved, Approved with Limitations, Pending, etc.', max_length=100),
        ),
    ]
