# Generated by Django 4.2.8 on 2025-12-28 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('styles', '0004_add_material_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='translation_status',
            field=models.CharField(choices=[('pending', 'Pending Translation'), ('confirmed', 'Translation Confirmed')], default='pending', help_text='Translation confirmation status', max_length=20),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bom_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='constructionstep',
            name='translation_status',
            field=models.CharField(choices=[('pending', 'Pending Translation'), ('confirmed', 'Translation Confirmed')], default='pending', help_text='Translation confirmation status', max_length=20),
        ),
        migrations.AddField(
            model_name='constructionstep',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constructionstep',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_construction_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='measurement',
            name='translation_status',
            field=models.CharField(choices=[('pending', 'Pending Translation'), ('confirmed', 'Translation Confirmed')], default='pending', help_text='Translation confirmation status', max_length=20),
        ),
        migrations.AddField(
            model_name='measurement',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_measurements', to=settings.AUTH_USER_MODEL),
        ),
    ]
