# Generated by Django 4.2.8 on 2025-12-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0005_add_verification_and_translation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="style",
            name="target_due_date",
            field=models.DateField(
                blank=True,
                help_text="Target due date for this style (for risk calculation)",
                null=True,
            ),
        ),
    ]
