# Generated by Django 4.2.8 on 2026-01-02 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("styles", "0006_add_target_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomitem",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization (tenant) - denormalized for query performance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bom_items",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="constructionstep",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization (tenant) - denormalized for query performance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="construction_steps",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization (tenant) - denormalized for query performance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="stylerevision",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization (tenant) - denormalized from style for query performance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="style_revisions",
                to="core.organization",
            ),
        ),
    ]
