# Generated by Django 4.2.8 on 2026-01-02 12:40
# SaaS-Ready: Backfill organization FK for styles models

from django.db import migrations


def backfill_organization(apps, schema_editor):
    """
    Backfill organization FK from parent models:
    - StyleRevision: get organization from Style
    - BOMItem: get organization from StyleRevision -> Style
    - Measurement: get organization from StyleRevision -> Style
    - ConstructionStep: get organization from StyleRevision -> Style
    """
    StyleRevision = apps.get_model('styles', 'StyleRevision')
    BOMItem = apps.get_model('styles', 'BOMItem')
    Measurement = apps.get_model('styles', 'Measurement')
    ConstructionStep = apps.get_model('styles', 'ConstructionStep')

    # Backfill StyleRevision
    for revision in StyleRevision.objects.select_related('style').iterator():
        if revision.style and revision.style.organization_id:
            revision.organization_id = revision.style.organization_id
            revision.save(update_fields=['organization_id'])

    # Backfill BOMItem
    for item in BOMItem.objects.select_related('revision__style').iterator():
        if item.revision and item.revision.style and item.revision.style.organization_id:
            item.organization_id = item.revision.style.organization_id
            item.save(update_fields=['organization_id'])

    # Backfill Measurement
    for m in Measurement.objects.select_related('revision__style').iterator():
        if m.revision and m.revision.style and m.revision.style.organization_id:
            m.organization_id = m.revision.style.organization_id
            m.save(update_fields=['organization_id'])

    # Backfill ConstructionStep
    for step in ConstructionStep.objects.select_related('revision__style').iterator():
        if step.revision and step.revision.style and step.revision.style.organization_id:
            step.organization_id = step.revision.style.organization_id
            step.save(update_fields=['organization_id'])


def reverse_backfill(apps, schema_editor):
    """Reverse: set all organization FKs back to NULL"""
    StyleRevision = apps.get_model('styles', 'StyleRevision')
    BOMItem = apps.get_model('styles', 'BOMItem')
    Measurement = apps.get_model('styles', 'Measurement')
    ConstructionStep = apps.get_model('styles', 'ConstructionStep')

    StyleRevision.objects.update(organization=None)
    BOMItem.objects.update(organization=None)
    Measurement.objects.update(organization=None)
    ConstructionStep.objects.update(organization=None)


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0007_add_organization_fk"),
    ]

    operations = [
        migrations.RunPython(backfill_organization, reverse_backfill),
    ]
