# Generated by Django 4.2.8 on 2026-01-06 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0009_add_translation_content_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measurement",
            name="point_name_zh",
        ),
        migrations.RemoveField(
            model_name="measurement",
            name="translated_at",
        ),
        migrations.RemoveField(
            model_name="measurement",
            name="translated_by",
        ),
    ]
