# Generated by Django 4.2.8 on 2026-01-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0010_add_uploaded_document"),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='point_name_zh',
            field=models.CharField(max_length=100, blank=True, help_text='Chinese translation of measurement point name'),
        ),
    ]
