# Generated by Django 4.2.8 on 2026-01-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0011_add_measurement_point_name_zh"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomitem",
            name="confirmed_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="確認用量（Marker Report / 樣衣實際）",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="consumption_confirmed_at",
            field=models.DateTimeField(blank=True, help_text="用量確認時間", null=True),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="consumption_history",
            field=models.JSONField(blank=True, default=list, help_text="用量變更歷史記錄"),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="consumption_locked_at",
            field=models.DateTimeField(blank=True, help_text="用量鎖定時間", null=True),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="locked_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="鎖定用量（大貨確認後不可改）",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="pre_estimate_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="預估用量（工廠經驗值，用於 RFQ）",
                max_digits=10,
                null=True,
            ),
        ),
    ]
