# Generated by Django 4.2.8 on 2026-01-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0012_add_consumption_stages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bomitem",
            name="unit",
            field=models.CharField(
                blank=True,
                default="YD",
                help_text="e.g., yards, meters, pcs",
                max_length=20,
            ),
        ),
    ]
