# Generated by Django 4.2.8 on 2026-01-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0013_add_unit_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomitem",
            name="sample_confirmed_at",
            field=models.DateTimeField(blank=True, help_text="樣衣用量確認時間", null=True),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="sample_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="樣衣用量（打樣實際消耗）",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="confirmed_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="確認用量（Marker Report 調整後）",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="consumption_maturity",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("pre_estimate", "Pre-Estimate"),
                    ("sample", "Sample"),
                    ("confirmed", "Confirmed"),
                    ("locked", "Locked"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
