# Generated by Django 5.0.14 on 2026-01-27 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_saas_ready_fields"),
        ("styles", "0014_add_sample_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Brand code, e.g., LLL, NIKE, ADIDAS",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full brand name, e.g., lululemon athletica",
                        max_length=200,
                    ),
                ),
                (
                    "bom_format",
                    models.CharField(
                        choices=[
                            ("auto", "Auto Detect"),
                            (
                                "vertical_table",
                                "Vertical Table (columns: Material, Supplier, Price...)",
                            ),
                            (
                                "horizontal_table",
                                "Horizontal Table (rows: materials, columns: colors)",
                            ),
                            ("free_text", "Free Text (FABRIC INFO sections)"),
                            ("mixed", "Mixed Format"),
                        ],
                        default="auto",
                        help_text="Default BOM format for this brand's tech packs",
                        max_length=50,
                    ),
                ),
                (
                    "bom_extraction_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom extraction rules: column mappings, section keywords, etc.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "db_table": "brands",
                "ordering": ["name"],
                "unique_together": {("organization", "code")},
            },
        ),
        migrations.AddField(
            model_name="style",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                help_text="Brand determines BOM extraction format",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="styles",
                to="styles.brand",
            ),
        ),
    ]
