# Generated by Django 4.2.8 on 2025-12-28 03:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0004_add_material_status'),
        ('parsing', '0002_add_file_to_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costing_type', models.CharField(choices=[('sample', 'Sample Costing'), ('bulk', 'Bulk Costing')], help_text='Sample or Bulk costing', max_length=20)),
                ('version_no', models.IntegerField(help_text='Version number (1, 2, 3...)')),
                ('is_current', models.BooleanField(default=True, help_text='Is this the current version?')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Labor cost per unit', max_digits=10)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overhead cost per unit', max_digits=10)),
                ('freight_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Freight cost per unit', max_digits=10)),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Packaging cost per unit', max_digits=10)),
                ('testing_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Testing cost per unit', max_digits=10)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Margin percentage (e.g., 30.00 for 30%)', max_digits=5)),
                ('wastage_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Global wastage percentage (Phase 1: applies to all lines)', max_digits=5)),
                ('material_cost', models.DecimalField(decimal_places=4, help_text='Total material cost (sum of line_cost)', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=4, help_text='Total COGS (material + labor + overhead + freight + packaging + testing)', max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Final unit price (Sample price or FOB price)', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Notes for this costing version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheets', to='parsing.revision')),
            ],
            options={
                'db_table': 'cost_sheets',
                'ordering': ['-version_no'],
            },
        ),
        migrations.CreateModel(
            name='CostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(help_text='Material name snapshot', max_length=255)),
                ('supplier', models.CharField(help_text='Supplier snapshot', max_length=255)),
                ('category', models.CharField(help_text='Category snapshot (fabric/trim/packaging/label)', max_length=50)),
                ('unit', models.CharField(help_text='Unit snapshot (Yard/Meter/PCS)', max_length=20)),
                ('consumption', models.DecimalField(decimal_places=4, help_text='Consumption per garment (snapshot)', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Unit price snapshot', max_digits=10)),
                ('line_cost', models.DecimalField(decimal_places=4, help_text='Line cost = consumption × unit_price × (1 + wastage%)', max_digits=12)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (0-based index)')),
                ('bom_item', models.ForeignKey(help_text='Reference to original BOM item (for traceability)', on_delete=django.db.models.deletion.PROTECT, to='styles.bomitem')),
                ('cost_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='costing.costsheet')),
            ],
            options={
                'db_table': 'cost_lines',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='costsheet',
            index=models.Index(fields=['revision', 'costing_type', 'is_current'], name='cost_sheets_revisio_237ee7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costsheet',
            unique_together={('revision', 'costing_type', 'version_no')},
        ),
        migrations.AddIndex(
            model_name='costline',
            index=models.Index(fields=['cost_sheet', 'sort_order'], name='cost_lines_cost_sh_042e25_idx'),
        ),
    ]
