# Generated by Django 4.2.8 on 2025-12-28 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0004_add_material_status'),
        ('costing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costsheet',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheets', to='styles.stylerevision'),
        ),
    ]
