# Generated by Django 4.2.8 on 2025-12-28 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costing', '0002_alter_costsheet_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='costsheet',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_sheets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('archived', 'Archived')], default='draft', help_text='Status: draft/sent/archived', max_length=20),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_sheets_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
