# Generated by Django 4.2.8 on 2025-12-29 13:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0005_add_verification_and_translation_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("costing", "0003_costsheet_created_by_costsheet_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostSheetGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_sheet_groups",
                        to="styles.style",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Sheet Group",
                "verbose_name_plural": "Cost Sheet Groups",
                "db_table": "cost_sheet_groups",
            },
        ),
        migrations.CreateModel(
            name="CostSheetVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_no",
                    models.IntegerField(help_text="Version number within costing_type"),
                ),
                (
                    "costing_type",
                    models.CharField(
                        choices=[
                            ("sample", "Sample Costing"),
                            ("bulk", "Bulk Costing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "overhead_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "freight_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "packing_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "margin_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("30.00"), max_digits=5
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=10
                    ),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("superseded", "Superseded"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True,
                        help_text='Why was this version created (e.g., "Client requested price reduction")',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which version this was cloned from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cloned_versions",
                        to="costing.costsheetversion",
                    ),
                ),
                (
                    "cost_sheet_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="costing.costsheetgroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cost_sheet_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_cost_sheet_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which version superseded this one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_versions",
                        to="costing.costsheetversion",
                    ),
                ),
                (
                    "techpack_revision",
                    models.ForeignKey(
                        help_text="Tech Pack revision used for this quote",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="styles.stylerevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Sheet Version",
                "verbose_name_plural": "Cost Sheet Versions",
                "db_table": "cost_sheet_versions",
                "ordering": ["costing_type", "-version_no"],
            },
        ),
        migrations.CreateModel(
            name="UsageScenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("sample_quote", "Sample Quote"),
                            ("bulk_quote", "Bulk Quote"),
                            ("procurement_plan", "Procurement Plan"),
                            ("actual", "Actual Usage"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version_no", models.IntegerField(default=1)),
                (
                    "wastage_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="全局 wastage percentage（可被 UsageLine 覆寫）",
                        max_digits=5,
                    ),
                ),
                (
                    "rounding_rule",
                    models.CharField(
                        default="round_up",
                        help_text="Round up/down rule for consumption calculation",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("superseded", "Superseded")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_usage_scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_first_by_cost_sheet",
                    models.ForeignKey(
                        blank=True,
                        help_text="第一個鎖定此 scenario 的 CostSheetVersion（審計用）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="first_locked_scenarios",
                        to="costing.costsheetversion",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_scenarios",
                        to="styles.stylerevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Scenario",
                "verbose_name_plural": "Usage Scenarios",
                "db_table": "usage_scenarios",
                "ordering": ["purpose", "-version_no"],
                "unique_together": {("revision", "purpose", "version_no")},
            },
        ),
        migrations.AddField(
            model_name="costsheetversion",
            name="usage_scenario",
            field=models.ForeignKey(
                help_text="Usage scenario snapshot for this quote",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_sheet_versions",
                to="costing.usagescenario",
            ),
        ),
        migrations.CreateModel(
            name="CostLineV2",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_revision_id",
                    models.UUIDField(help_text="StyleRevision ID (for traceability)"),
                ),
                (
                    "source_usage_scenario_id",
                    models.UUIDField(help_text="UsageScenario ID (for traceability)"),
                ),
                (
                    "source_usage_scenario_version_no",
                    models.IntegerField(
                        help_text="UsageScenario version_no (for traceability)"
                    ),
                ),
                (
                    "source_bom_item_id",
                    models.UUIDField(help_text="BOMItem ID (for traceability)"),
                ),
                (
                    "source_usage_line_id",
                    models.UUIDField(help_text="UsageLine ID (for traceability)"),
                ),
                ("material_name", models.CharField(max_length=200)),
                ("material_name_zh", models.CharField(blank=True, max_length=200)),
                ("category", models.CharField(max_length=50)),
                ("supplier", models.CharField(blank=True, max_length=200)),
                ("supplier_article_no", models.CharField(blank=True, max_length=100)),
                ("unit", models.CharField(max_length=20)),
                (
                    "consumption_snapshot",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Original consumption from UsageLine",
                        max_digits=10,
                    ),
                ),
                (
                    "consumption_adjusted",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Adjusted consumption (editable in Draft)",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_price_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original unit price from BOMItem",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_price_adjusted",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Adjusted unit price (editable in Draft)",
                        max_digits=10,
                    ),
                ),
                (
                    "is_consumption_adjusted",
                    models.BooleanField(
                        default=False,
                        help_text="True if consumption was manually adjusted",
                    ),
                ),
                (
                    "is_price_adjusted",
                    models.BooleanField(
                        default=False,
                        help_text="True if unit price was manually adjusted",
                    ),
                ),
                (
                    "adjustment_reason",
                    models.CharField(
                        blank=True,
                        help_text='Why was this adjusted (e.g., "Client negotiation")',
                        max_length=200,
                    ),
                ),
                (
                    "line_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Line cost = consumption_adjusted × unit_price_adjusted",
                        max_digits=10,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("adjusted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjusted_cost_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cost_sheet_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_lines",
                        to="costing.costsheetversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Line (v2)",
                "verbose_name_plural": "Cost Lines (v2)",
                "db_table": "cost_lines_v2",
                "ordering": ["sort_order", "category", "material_name"],
            },
        ),
        migrations.CreateModel(
            name="UsageLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consumption",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Consumption per garment",
                        max_digits=10,
                    ),
                ),
                (
                    "consumption_unit",
                    models.CharField(
                        help_text="e.g., yards, meters, pcs", max_length=20
                    ),
                ),
                (
                    "consumption_status",
                    models.CharField(
                        choices=[
                            ("estimated", "Estimated"),
                            ("confirmed", "Confirmed"),
                            ("actual", "Actual"),
                        ],
                        default="estimated",
                        max_length=20,
                    ),
                ),
                (
                    "wastage_pct_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override scenario wastage_pct for this specific line",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "bom_item",
                    models.ForeignKey(
                        help_text="Reference to BOM item (WHAT material)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="styles.bomitem",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_usage_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usage_scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_lines",
                        to="costing.usagescenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Line",
                "verbose_name_plural": "Usage Lines",
                "db_table": "usage_lines",
                "ordering": ["sort_order", "bom_item__category"],
                "unique_together": {("usage_scenario", "bom_item")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="costsheetversion",
            unique_together={("cost_sheet_group", "costing_type", "version_no")},
        ),
        migrations.AddConstraint(
            model_name="costsheetgroup",
            constraint=models.UniqueConstraint(
                fields=("style",), name="unique_cost_sheet_group_per_style"
            ),
        ),
    ]
