# Generated by Django 4.2.8 on 2025-12-29 13:52

from django.db import migrations
from decimal import Decimal


def migrate_consumption_to_usage_lines(apps, schema_editor):
    """
    M2: BOMItem.consumption → UsageLine

    對每個 StyleRevision:
      1. 創建 UsageScenario (purpose='bulk_quote', version_no=1, status='draft')
      2. 對該 revision 的所有 BOMItem 創建 UsageLine
    """
    StyleRevision = apps.get_model('styles', 'StyleRevision')
    BOMItem = apps.get_model('styles', 'BOMItem')
    UsageScenario = apps.get_model('costing', 'UsageScenario')
    UsageLine = apps.get_model('costing', 'UsageLine')

    for revision in StyleRevision.objects.all():
        # 1. 創建 bulk_quote v1 scenario
        scenario = UsageScenario.objects.create(
            revision=revision,
            purpose='bulk_quote',
            version_no=1,
            wastage_pct=Decimal('5.00'),
            status='draft',
            notes='Migrated from BOMItem.consumption (M2)'
        )

        # 2. 對每個 BOMItem 創建 UsageLine
        bom_items = BOMItem.objects.filter(revision=revision).order_by('item_number')
        usage_lines = []

        for idx, bom_item in enumerate(bom_items, start=1):
            consumption = bom_item.consumption if bom_item.consumption else Decimal('0.0000')

            # 決定 consumption_status
            if consumption > 0:
                consumption_status = 'confirmed'
            else:
                consumption_status = 'estimated'

            usage_line = UsageLine(
                usage_scenario=scenario,
                bom_item=bom_item,
                consumption=consumption,
                consumption_unit=bom_item.unit,
                consumption_status=consumption_status,
                sort_order=idx * 10  # 10, 20, 30, ... (留空間給插入)
            )
            usage_lines.append(usage_line)

        # Bulk create
        if usage_lines:
            UsageLine.objects.bulk_create(usage_lines)

        print(f"✓ Migrated {len(usage_lines)} BOMItems → UsageLines for {revision}")


def reverse_migration(apps, schema_editor):
    """
    反向遷移：刪除所有 UsageScenario 和 UsageLine
    """
    UsageScenario = apps.get_model('costing', 'UsageScenario')
    UsageLine = apps.get_model('costing', 'UsageLine')

    UsageLine.objects.all().delete()
    UsageScenario.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("costing", "0004_add_phase23_models"),
        ("styles", "0005_add_verification_and_translation_fields"),  # BOMItem exists
    ]

    operations = [
        migrations.RunPython(migrate_consumption_to_usage_lines, reverse_migration),
    ]
