# Generated by Django 4.2.8 on 2025-12-29 13:59

from django.db import migrations
from decimal import Decimal
import uuid


def migrate_old_cost_sheets(apps, schema_editor):
    """
    M3: Old CostSheet → CostSheetVersion + CostLineV2

    對每個 Style:
      1. 創建 CostSheetGroup(style)
      2. 對旧 cost sheets:
         - 創建 CostSheetVersion
         - 綁定 evidence (techpack_revision + usage_scenario)
         - 生成 CostLineV2（快照模式）
    """
    Style = apps.get_model('styles', 'Style')
    StyleRevision = apps.get_model('styles', 'StyleRevision')
    OldCostSheet = apps.get_model('costing', 'CostSheet')
    OldCostLine = apps.get_model('costing', 'CostLine')

    CostSheetGroup = apps.get_model('costing', 'CostSheetGroup')
    CostSheetVersion = apps.get_model('costing', 'CostSheetVersion')
    CostLineV2 = apps.get_model('costing', 'CostLineV2')
    UsageScenario = apps.get_model('costing', 'UsageScenario')

    for style in Style.objects.all():
        # 1. 創建或獲取 CostSheetGroup
        group, _ = CostSheetGroup.objects.get_or_create(style=style)

        # 2. 獲取該 style 的所有旧 cost sheets
        old_sheets = OldCostSheet.objects.filter(
            revision__style=style
        ).order_by('created_at')

        # 版本號計數器（按 costing_type 分別計數）
        version_map = {'sample': 0, 'bulk': 0}

        for old_sheet in old_sheets:
            costing_type = old_sheet.costing_type
            version_map[costing_type] += 1

            # 找到對應的 usage_scenario（M2 創建的 bulk_quote v1）
            usage_scenario = UsageScenario.objects.filter(
                revision=old_sheet.revision,
                purpose='bulk_quote',
                version_no=1
            ).first()

            if not usage_scenario:
                print(f"⚠️  No usage_scenario for {old_sheet.revision}, skipping...")
                continue

            # 3. 創建新 CostSheetVersion
            new_version = CostSheetVersion.objects.create(
                cost_sheet_group=group,
                version_no=version_map[costing_type],
                costing_type=costing_type,

                # ⭐ Evidence 綁定
                techpack_revision=old_sheet.revision,
                usage_scenario=usage_scenario,

                # ⭐ 複製舊字段
                labor_cost=old_sheet.labor_cost,
                overhead_cost=old_sheet.overhead_cost,
                freight_cost=getattr(old_sheet, 'freight_cost', Decimal('0.00')),
                packing_cost=getattr(old_sheet, 'packaging_cost', Decimal('0.00')),
                margin_pct=old_sheet.margin_pct,

                material_cost=old_sheet.material_cost,
                total_cost=old_sheet.total_cost,
                unit_price=old_sheet.unit_price,

                # ⭐ 狀態：假設舊數據已提交
                status='submitted',
                created_by=old_sheet.created_by,
                created_at=old_sheet.created_at,
                submitted_at=old_sheet.created_at,
                submitted_by=old_sheet.created_by
            )

            # 4. 迁移 CostLines → CostLineV2
            cost_lines = []
            for idx, old_line in enumerate(old_sheet.lines.all()):
                # 嘗試找到對應的 UsageLine
                usage_line = None
                if old_line.bom_item:
                    usage_line = usage_scenario.usage_lines.filter(
                        bom_item=old_line.bom_item
                    ).first()

                cost_line = CostLineV2(
                    cost_sheet_version=new_version,

                    # ⭐ Source 追蹤
                    source_revision_id=old_sheet.revision.id,
                    source_usage_scenario_id=usage_scenario.id,
                    source_usage_scenario_version_no=1,
                    source_bom_item_id=old_line.bom_item.id if old_line.bom_item else uuid.UUID('00000000-0000-0000-0000-000000000000'),
                    source_usage_line_id=usage_line.id if usage_line else uuid.UUID('00000000-0000-0000-0000-000000000000'),

                    # ⭐ 快照數據
                    material_name=old_line.material_name,
                    material_name_zh='',  # 舊數據無中文名
                    category=old_line.category,
                    supplier=old_line.supplier,
                    supplier_article_no='',  # 舊數據無此字段
                    unit=old_line.unit,

                    # ⭐ Snapshot = Adjusted（舊數據無調整）
                    consumption_snapshot=old_line.consumption,
                    consumption_adjusted=old_line.consumption,
                    unit_price_snapshot=old_line.unit_price,
                    unit_price_adjusted=old_line.unit_price,

                    # 調整標記
                    is_consumption_adjusted=False,
                    is_price_adjusted=False,
                    adjustment_reason='',

                    line_cost=old_line.line_cost,
                    sort_order=old_line.sort_order
                )
                cost_lines.append(cost_line)

            if cost_lines:
                CostLineV2.objects.bulk_create(cost_lines)

            print(f"✓ Migrated CostSheet v{new_version.version_no} ({costing_type}) with {len(cost_lines)} lines for {style}")


def reverse_migration(apps, schema_editor):
    """
    反向遷移：刪除所有 CostSheetVersion 和 CostLineV2
    """
    CostSheetVersion = apps.get_model('costing', 'CostSheetVersion')
    CostLineV2 = apps.get_model('costing', 'CostLineV2')
    CostSheetGroup = apps.get_model('costing', 'CostSheetGroup')

    CostLineV2.objects.all().delete()
    CostSheetVersion.objects.all().delete()
    CostSheetGroup.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("costing", "0005_migrate_consumption_to_usage_lines"),
        ("styles", "0005_add_verification_and_translation_fields"),
    ]

    operations = [
        migrations.RunPython(migrate_old_cost_sheets, reverse_migration),
    ]
