# Generated by Django 4.2.8 on 2026-01-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costing", "0006_migrate_old_costsheet_to_new_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usagescenario",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("sample_quote", "Sample Quote"),
                    ("bulk_quote", "Bulk Quote"),
                    ("procurement_plan", "Procurement Plan"),
                    ("actual", "Actual Usage"),
                    ("sample_guidance", "Sample Guidance"),
                    ("sample_actual", "Sample Actual"),
                ],
                max_length=50,
            ),
        ),
    ]
