# Generated by Django 4.2.8 on 2025-12-19 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marker_date', models.DateField()),
                ('fabric_width', models.DecimalField(decimal_places=2, help_text='Fabric width in cm or inches', max_digits=6)),
                ('fabric_width_unit', models.CharField(default='cm', max_length=10)),
                ('consumption_per_piece', models.DecimalField(decimal_places=4, help_text='Yards or meters per piece from marker', max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, help_text='Marker efficiency percentage', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marker Report',
                'verbose_name_plural': 'Marker Reports',
                'db_table': 'marker_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemBOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumption_per_piece', models.DecimalField(decimal_places=4, help_text='Actual consumption for this specific order', max_digits=10)),
                ('consumption_maturity', models.CharField(choices=[('unknown', 'Unknown'), ('pre_estimate', 'Pre-Estimate'), ('confirmed', 'Confirmed'), ('locked', 'Locked')], default='unknown', max_length=20)),
                ('total_consumption', models.DecimalField(decimal_places=4, help_text='Order quantity × consumption_per_piece', max_digits=12)),
                ('source', models.CharField(blank=True, help_text="e.g., 'marker_report', 'trim_rule_TRIM-001', 'manual_entry'", max_length=50)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Item BOM',
                'verbose_name_plural': 'Order Item BOMs',
                'db_table': 'order_item_bom',
                'ordering': ['template_bom_item__item_number'],
            },
        ),
        migrations.CreateModel(
            name='TrimMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measured_value', models.DecimalField(decimal_places=2, help_text='Actual measured value from sample', max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('measurement_point', models.CharField(max_length=100)),
                ('applied_rule_id', models.CharField(blank=True, help_text='e.g., TRIM-001', max_length=20)),
                ('calculated_consumption', models.DecimalField(decimal_places=4, help_text='Result after applying rule', max_digits=10)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Trim Measurement',
                'verbose_name_plural': 'Trim Measurements',
                'db_table': 'trim_measurements',
                'ordering': ['-measured_at'],
            },
        ),
    ]
