# Generated by Django 4.2.8 on 2025-12-19 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('consumption', '0001_initial'),
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimmeasurement',
            name='bom_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trim_measurements', to='styles.bomitem'),
        ),
        migrations.AddField(
            model_name='trimmeasurement',
            name='measured_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trimmeasurement',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trim_measurements', to='orders.salesorderitem'),
        ),
        migrations.AddField(
            model_name='orderitembom',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='orders.salesorderitem'),
        ),
        migrations.AddField(
            model_name='orderitembom',
            name='source_reference',
            field=models.ForeignKey(blank=True, help_text='Link to marker report if source is marker', null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumption.markerreport'),
        ),
        migrations.AddField(
            model_name='orderitembom',
            name='template_bom_item',
            field=models.ForeignKey(help_text='The template BOM item this is based on', on_delete=django.db.models.deletion.PROTECT, related_name='order_instances', to='styles.bomitem'),
        ),
        migrations.AddField(
            model_name='markerreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markerreport',
            name='marker_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document'),
        ),
        migrations.AddField(
            model_name='markerreport',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marker_reports', to='orders.salesorderitem'),
        ),
    ]
