# Generated by Django 4.2.8 on 2025-12-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitembom',
            name='confirmed_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Confirmed consumption (from marker/sample, for Production PO)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitembom',
            name='locked_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Locked consumption (frozen before PP, for final Production PO)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitembom',
            name='pre_estimate_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Estimated consumption (for RFQ PO)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitembom',
            name='source_ref',
            field=models.CharField(blank=True, help_text="Reference ID/code (e.g., 'MARKER-2024-001', 'TRIM-005', marker UUID)", max_length=200),
        ),
        migrations.AddField(
            model_name='orderitembom',
            name='source_type',
            field=models.CharField(blank=True, choices=[('tech_pack', 'Tech Pack'), ('marker', 'Marker Report'), ('trim_rule', 'Trim Rule'), ('manual', 'Manual Entry')], help_text='Type of evidence for consumption value', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitembom',
            name='consumption_per_piece',
            field=models.DecimalField(decimal_places=4, help_text='Actual consumption for this specific order (current active value)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitembom',
            name='source',
            field=models.CharField(blank=True, help_text="DEPRECATED: Use source_type instead. e.g., 'marker_report', 'trim_rule_TRIM-001', 'manual_entry'", max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitembom',
            name='source_reference',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use source_ref instead. Link to marker report if source is marker', null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumption.markerreport'),
        ),
    ]
