# Generated by Django 4.2.8 on 2025-12-19 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('techpack', 'Tech Pack'), ('bom', 'BOM'), ('spec', 'Specification'), ('artwork', 'Artwork'), ('marker', 'Marker Report'), ('sample_photo', 'Sample Photo'), ('other', 'Other')], help_text='Purpose/usage of the document', max_length=50)),
                ('file_kind', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('docx', 'Word'), ('img', 'Image'), ('csv', 'CSV'), ('other', 'Other')], help_text='File format', max_length=20)),
                ('source', models.CharField(choices=[('customer', 'Customer'), ('internal', 'Internal'), ('vendor', 'Vendor')], default='customer', help_text='Origin of the document', max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='Size in bytes')),
                ('file_hash', models.CharField(db_index=True, help_text='SHA256 hash for duplicate detection', max_length=64)),
                ('content_type', models.CharField(blank=True, help_text='MIME type (e.g., application/pdf)', max_length=100)),
                ('storage_key', models.CharField(help_text='Storage path in S3/MinIO', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed', 'Upload Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.organization')),
                ('style_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='styles.stylerevision')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
