# Generated by Django 4.2.8 on 2025-12-19 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, help_text='Raw AI extraction results', null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of issues/warnings from AI')),
                ('ai_model', models.CharField(blank=True, max_length=50)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('api_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='documents.document')),
                ('style_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='styles.stylerevision')),
            ],
            options={
                'verbose_name': 'Extraction Run',
                'verbose_name_plural': 'Extraction Runs',
                'db_table': 'extraction_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('bom_item', 'BOM Item'), ('measurement', 'Measurement'), ('construction', 'Construction Step')], max_length=20)),
                ('ai_data', models.JSONField(help_text='AI extracted data for this item')),
                ('ai_confidence', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('corrected', 'Corrected')], default='pending', max_length=20)),
                ('corrected_data', models.JSONField(blank=True, help_text='Human-corrected data', null=True)),
                ('correction_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='parsing.extractionrun')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Draft Review Item',
                'verbose_name_plural': 'Draft Review Items',
                'db_table': 'draft_review_items',
                'ordering': ['item_type', '-ai_confidence'],
            },
        ),
    ]
