# Generated by Django 4.2.8 on 2025-12-21 09:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('callout', 'Callout'), ('legend', 'Legend'), ('section_title', 'Section Title'), ('description', 'Description'), ('table', 'Table')], max_length=30)),
                ('bbox_x', models.FloatField()),
                ('bbox_y', models.FloatField()),
                ('bbox_width', models.FloatField()),
                ('bbox_height', models.FloatField()),
                ('source_text', models.TextField(help_text='原文（英文，locked，永不覆寫）')),
                ('translated_text', models.TextField(help_text='AI 翻譯（中文，機翻初稿）')),
                ('edited_text', models.TextField(blank=True, help_text='人工修正後的中文（可選）', null=True)),
                ('status', models.CharField(choices=[('auto', 'Auto Translated'), ('edited', 'Edited'), ('approved', 'Approved')], default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Draft Block',
                'verbose_name_plural': 'Draft Blocks',
                'db_table': 'draft_blocks',
                'ordering': ['page__page_number', 'bbox_y', 'bbox_x'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Tech Pack PDF 檔案', upload_to='techpacks/')),
                ('filename', models.CharField(max_length=255)),
                ('page_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('reviewing', 'Reviewing'), ('completed', 'Completed')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revisions',
                'db_table': 'revisions',
            },
        ),
        migrations.CreateModel(
            name='RevisionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='parsing.revision')),
            ],
            options={
                'verbose_name': 'Revision Page',
                'verbose_name_plural': 'Revision Pages',
                'db_table': 'revision_pages',
                'ordering': ['page_number'],
                'unique_together': {('revision', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='DraftBlockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_text', models.TextField()),
                ('new_text', models.TextField()),
                ('changed_by', models.CharField(blank=True, max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='parsing.draftblock')),
            ],
            options={
                'verbose_name': 'Draft Block History',
                'verbose_name_plural': 'Draft Block Histories',
                'db_table': 'draft_block_histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='draftblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='parsing.revisionpage'),
        ),
        migrations.AddIndex(
            model_name='draftblock',
            index=models.Index(fields=['page', 'block_type'], name='draft_block_page_id_970846_idx'),
        ),
        migrations.AddIndex(
            model_name='draftblock',
            index=models.Index(fields=['status'], name='draft_block_status_06f1b8_idx'),
        ),
    ]
