# Generated by Django 4.2.8 on 2026-01-06 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0010_add_uploaded_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_saas_ready_fields"),
        ("parsing", "0002_add_file_to_revision"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(max_length=500, upload_to="uploads/%Y/%m/")),
                ("filename", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        help_text="File extension: pdf, xlsx, csv, etc.", max_length=10
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "classification_result",
                    models.JSONField(
                        blank=True,
                        help_text='\n        AI classification result:\n        {\n            "file_type": "mixed" | "tech_pack_only" | "bom_only" | "measurement_only",\n            "total_pages": 30,\n            "pages": [\n                {"page": 1, "type": "tech_pack", "confidence": 0.95},\n                {"page": 2, "type": "measurement_table", "confidence": 0.98},\n                {"page": 3, "type": "bom_table", "confidence": 0.92},\n                ...\n            ]\n        }\n        ',
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("classifying", "AI Classifying"),
                            ("classified", "Classified"),
                            ("extracting", "AI Extracting"),
                            ("extracted", "Extracted"),
                            ("reviewing", "Under Review"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "extraction_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of errors during extraction",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_documents",
                        to="core.organization",
                    ),
                ),
                (
                    "style_revision",
                    models.ForeignKey(
                        blank=True,
                        help_text="Created StyleRevision after successful extraction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to="styles.stylerevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uploaded Document",
                "verbose_name_plural": "Uploaded Documents",
                "db_table": "uploaded_documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
