# Generated by Django 4.2.8 on 2026-01-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parsing", "0003_add_uploaded_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="tech_pack_revision",
            field=models.ForeignKey(
                blank=True,
                help_text="Created TechPackRevision for draft review (P0 interface)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to="parsing.revision",
            ),
        ),
    ]
