# Generated by Django 4.2.8 on 2026-01-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parsing", "0004_add_tech_pack_revision_to_uploaded_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftblock",
            name="overlay_visible",
            field=models.BooleanField(default=True, help_text="是否在 MWO 中顯示此翻譯"),
        ),
        migrations.AddField(
            model_name="draftblock",
            name="overlay_x",
            field=models.FloatField(
                blank=True, help_text="翻譯文字框 X 位置（用戶調整後）", null=True
            ),
        ),
        migrations.AddField(
            model_name="draftblock",
            name="overlay_y",
            field=models.FloatField(
                blank=True, help_text="翻譯文字框 Y 位置（用戶調整後）", null=True
            ),
        ),
    ]
