# Generated by Django 4.2.8 on 2026-01-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parsing", "0005_add_overlay_and_techpack_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="classify_task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for async classification",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="extract_task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for async extraction",
                max_length=50,
                null=True,
            ),
        ),
    ]
