# Generated by Django 5.0.14 on 2026-01-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parsing", "0006_add_celery_task_id_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftblock",
            name="translation_error",
            field=models.TextField(blank=True, help_text="翻譯失敗時的錯誤訊息", null=True),
        ),
        migrations.AddField(
            model_name="draftblock",
            name="translation_retry_count",
            field=models.PositiveIntegerField(default=0, help_text="翻譯重試次數"),
        ),
        migrations.AddField(
            model_name="draftblock",
            name="translation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("translating", "Translating"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                help_text="翻譯處理狀態",
                max_length=20,
            ),
        ),
    ]
