# Generated by Django 4.2.8 on 2025-12-28 15:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('styles', '0005_add_verification_and_translation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('physical_ref', models.CharField(blank=True, help_text='Physical reference / package number', max_length=60)),
                ('quantity_made', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('in_production', 'In Production'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], db_index=True, default='in_production', max_length=16)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, db_index=True, null=True)),
                ('customer_feedback', models.TextField(blank=True)),
                ('fit_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'samples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleCostEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimate_version', models.IntegerField(default=1, help_text='Version number (starts from 1)', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='draft', max_length=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('breakdown_snapshot_json', models.JSONField(default=dict, help_text='{"materials": [...], "labor": [...], "overhead": [...]}')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('from_phase2_costing', 'From Phase 2 Costing')], default='manual', max_length=32)),
                ('source_revision_id', models.UUIDField(blank=True, help_text='Redundant record of source revision', null=True)),
                ('snapshot_hash', models.CharField(blank=True, help_text='SHA256 of canonical JSON', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sample_cost_estimates',
                'ordering': ['-estimate_version'],
            },
        ),
        migrations.CreateModel(
            name='SampleRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, help_text='Brand name (future: FK to Brand model)', max_length=120)),
                ('request_type', models.CharField(choices=[('proto', 'Proto Sample'), ('fit', 'Fit Sample'), ('sales', 'Sales Sample'), ('photo', 'Photo Sample'), ('marketing', 'Marketing Sample'), ('wear_test', 'Wear Test'), ('material_test', 'Material Test'), ('color_approval', 'Color Approval'), ('size_set', 'Size Set'), ('replacement', 'Replacement'), ('trade_show', 'Trade Show'), ('counter', 'Counter Sample'), ('sealed', 'Sealed Sample'), ('custom', 'Custom')], default='proto', max_length=32)),
                ('request_type_custom', models.CharField(blank=True, help_text="Required when request_type='custom'", max_length=80)),
                ('quantity_requested', models.IntegerField(default=1, help_text='Number of samples requested', validators=[django.core.validators.MinValueValidator(1)])),
                ('size_set_json', models.JSONField(blank=True, default=dict, help_text='{"sizes": ["S", "M"], "notes": "..."}')),
                ('purpose', models.TextField(blank=True, help_text='Purpose of this sample request')),
                ('need_quote_first', models.BooleanField(default=False, help_text='Requires quote approval before execution')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('quote_requested', 'Quote Requested'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('in_execution', 'In Execution'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=24)),
                ('approval_status', models.CharField(choices=[('na', 'N/A'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='na', max_length=16)),
                ('notes_internal', models.TextField(blank=True)),
                ('notes_customer', models.TextField(blank=True)),
                ('brand_context_json', models.JSONField(blank=True, default=dict, help_text='Brand-specific custom fields')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_requests_created', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(help_text='Source revision (Phase 2)', on_delete=django.db.models.deletion.CASCADE, related_name='sample_requests', to='styles.stylerevision')),
            ],
            options={
                'db_table': 'sample_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='T2POForSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_no', models.CharField(blank=True, db_index=True, help_text='Generated after issued', max_length=40)),
                ('supplier_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('source_revision_id', models.UUIDField(help_text='Source revision at snapshot time')),
                ('snapshot_at', models.DateTimeField(auto_now_add=True, help_text='When BOM was snapshotted')),
                ('snapshot_hash', models.CharField(help_text='SHA256 of canonical BOM JSON', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t2pos', to='samples.samplecostestimate')),
                ('sample_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t2pos', to='samples.samplerequest')),
            ],
            options={
                'db_table': 't2pos_for_sample',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleMWO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mwo_no', models.CharField(blank=True, help_text='Generated after issued', max_length=40)),
                ('factory_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source_revision_id', models.UUIDField()),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('bom_snapshot_json', models.JSONField(default=list, help_text='BOM snapshot at MWO generation time')),
                ('construction_snapshot_json', models.JSONField(default=list, help_text='Construction steps snapshot')),
                ('qc_snapshot_json', models.JSONField(blank=True, default=dict, help_text='QC checkpoints snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.samplecostestimate')),
                ('sample_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mwos', to='samples.samplerequest')),
            ],
            options={
                'db_table': 'sample_mwos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='samplecostestimate',
            name='sample_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='samples.samplerequest'),
        ),
        migrations.CreateModel(
            name='SampleAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.TextField(help_text='URL or path to file')),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('pdf', 'PDF'), ('other', 'Other')], default='photo', max_length=24)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='samples.sample')),
                ('sample_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='samples.samplerequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sample_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_mwo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='samples.samplemwo'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.samplerequest'),
        ),
        migrations.CreateModel(
            name='T2POLineForSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.IntegerField(help_text='Line number in PO')),
                ('material_name', models.CharField(max_length=200)),
                ('supplier_article_no', models.CharField(blank=True, max_length=80)),
                ('uom', models.CharField(help_text='Unit of measure: yd, m, pcs', max_length=16)),
                ('consumption_per_piece', models.DecimalField(decimal_places=4, default=0, help_text='Consumption per garment', max_digits=12)),
                ('wastage_pct', models.DecimalField(decimal_places=4, default=0, help_text='Wastage percentage (0.10 = 10%)', max_digits=6)),
                ('quantity_requested', models.DecimalField(decimal_places=4, default=0, help_text='qty × consumption × (1 + wastage)', max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text='quantity × unit_price', max_digits=12)),
                ('t2po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='samples.t2poforsample')),
            ],
            options={
                'db_table': 't2po_lines_for_sample',
                'ordering': ['line_no'],
                'indexes': [models.Index(fields=['t2po'], name='t2po_lines__t2po_id_bb8de8_idx'), models.Index(fields=['material_name'], name='t2po_lines__materia_80d6fb_idx')],
                'unique_together': {('t2po', 'line_no')},
            },
        ),
        migrations.AddIndex(
            model_name='t2poforsample',
            index=models.Index(fields=['sample_request', 'status'], name='t2pos_for_s_sample__caa47c_idx'),
        ),
        migrations.AddIndex(
            model_name='t2poforsample',
            index=models.Index(fields=['supplier_name', 'status'], name='t2pos_for_s_supplie_dda5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='t2poforsample',
            index=models.Index(fields=['po_no'], name='t2pos_for_s_po_no_7cc8a1_idx'),
        ),
        migrations.AddIndex(
            model_name='t2poforsample',
            index=models.Index(fields=['delivery_date'], name='t2pos_for_s_deliver_2bc6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='samplerequest',
            index=models.Index(fields=['revision', 'status'], name='sample_requ_revisio_7684fb_idx'),
        ),
        migrations.AddIndex(
            model_name='samplerequest',
            index=models.Index(fields=['brand_name', 'status'], name='sample_requ_brand_n_19dbfe_idx'),
        ),
        migrations.AddIndex(
            model_name='samplerequest',
            index=models.Index(fields=['due_date'], name='sample_requ_due_dat_26a6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='samplemwo',
            index=models.Index(fields=['factory_name', 'status'], name='sample_mwos_factory_813fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='samplemwo',
            index=models.Index(fields=['due_date'], name='sample_mwos_due_dat_1efde1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='samplemwo',
            unique_together={('sample_request',)},
        ),
        migrations.AddIndex(
            model_name='samplecostestimate',
            index=models.Index(fields=['sample_request', 'status'], name='sample_cost_sample__2e9e61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='samplecostestimate',
            unique_together={('sample_request', 'estimate_version')},
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['sample_request', 'status'], name='samples_sample__2be2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['delivered_date'], name='samples_deliver_091321_idx'),
        ),
    ]
