# Generated by Django 4.2.8 on 2026-01-01 06:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("costing", "0007_alter_usagescenario_purpose"),
        ("styles", "0006_add_target_due_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleActuals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "labor_minutes",
                    models.IntegerField(
                        blank=True, help_text="Actual labor time in minutes", null=True
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual labor cost",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "overhead_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "rework_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost of any rework required",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "waste_pct_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual wastage percentage",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "issues_notes",
                    models.TextField(
                        blank=True, help_text="Notes about issues encountered"
                    ),
                ),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sample Actuals",
                "verbose_name_plural": "Sample Actuals",
                "db_table": "sample_actuals",
            },
        ),
        migrations.CreateModel(
            name="SampleRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "run_no",
                    models.IntegerField(
                        help_text="Run number within request (1, 2, 3...)"
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("proto", "Proto Sample"),
                            ("fit", "Fit Sample"),
                            ("sales", "Sales Sample"),
                            ("photo", "Photo Sample"),
                            ("other", "Other"),
                        ],
                        default="proto",
                        max_length=24,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("target_due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("materials_planning", "Materials Planning"),
                            ("po_drafted", "PO Drafted"),
                            ("po_issued", "PO Issued"),
                            ("mwo_drafted", "MWO Drafted"),
                            ("mwo_issued", "MWO Issued"),
                            ("in_progress", "In Progress"),
                            ("sample_done", "Sample Done"),
                            ("actuals_recorded", "Actuals Recorded"),
                            ("costing_generated", "Costing Generated"),
                            ("quoted", "Quoted"),
                            ("accepted", "Accepted"),
                            ("revise_needed", "Revise Needed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status_updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sample_runs",
                "ordering": ["run_no"],
            },
        ),
        migrations.RemoveIndex(
            model_name="t2poforsample",
            name="t2pos_for_s_sample__caa47c_idx",
        ),
        migrations.AlterUniqueTogether(
            name="samplemwo",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="samplerequest",
            name="approval_status",
        ),
        migrations.AddField(
            model_name="samplemwo",
            name="is_latest",
            field=models.BooleanField(
                default=True, help_text="Is this the latest version for this run?"
            ),
        ),
        migrations.AddField(
            model_name="samplemwo",
            name="version_no",
            field=models.IntegerField(
                default=1, help_text="Version number within run (1, 2, 3...)"
            ),
        ),
        migrations.AddField(
            model_name="t2poforsample",
            name="is_latest",
            field=models.BooleanField(
                default=True, help_text="Is this the latest version for this run?"
            ),
        ),
        migrations.AddField(
            model_name="t2poforsample",
            name="version_no",
            field=models.IntegerField(
                default=1, help_text="Version number within run (1, 2, 3...)"
            ),
        ),
        migrations.AlterField(
            model_name="samplemwo",
            name="sample_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mwos_legacy",
                to="samples.samplerequest",
            ),
        ),
        migrations.AlterField(
            model_name="samplerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("on_hold", "On Hold"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="open",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="t2poforsample",
            name="sample_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="t2pos_legacy",
                to="samples.samplerequest",
            ),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="actual_usage",
            field=models.ForeignKey(
                blank=True,
                help_text="Actual usage recorded after sample done",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="costing.usagescenario",
            ),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="costing_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Generated costing version from actuals",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="costing.costsheetversion",
            ),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sample_runs_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="guidance_usage",
            field=models.ForeignKey(
                blank=True,
                help_text="Guidance usage scenario for materials planning",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="costing.usagescenario",
            ),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                help_text="Override revision for this run (if different from request)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="styles.stylerevision",
            ),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="sample_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="samples.samplerequest",
            ),
        ),
        migrations.AddField(
            model_name="sampleactuals",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sampleactuals",
            name="sample_run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actuals",
                to="samples.samplerun",
            ),
        ),
        migrations.AddField(
            model_name="samplemwo",
            name="sample_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mwos",
                to="samples.samplerun",
            ),
        ),
        migrations.AddField(
            model_name="t2poforsample",
            name="sample_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="t2pos",
                to="samples.samplerun",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="samplerun",
            unique_together={("sample_request", "run_no")},
        ),
    ]
