# Generated by Django 4.2.8 on 2026-01-01 06:29
# Split from 0002 to avoid AddIndex before AddField dependency issues

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samples", "0002_sampleactuals_samplerun_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="samplemwo",
            index=models.Index(
                fields=["sample_run", "version_no"],
                name="sample_mwos_sample__3ad680_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="samplemwo",
            index=models.Index(
                fields=["sample_run", "status"],
                name="sample_mwos_sample__860506_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="t2poforsample",
            index=models.Index(
                fields=["sample_run", "version_no"],
                name="t2pos_for_s_sample__a30471_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="t2poforsample",
            index=models.Index(
                fields=["sample_run", "status"],
                name="t2pos_for_s_sample__f46767_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="samplerun",
            index=models.Index(
                fields=["sample_request", "status"],
                name="sample_runs_sample__082739_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="samplerun",
            index=models.Index(
                fields=["status", "target_due_date"],
                name="sample_runs_status_74048f_idx",
            ),
        ),
    ]
