# Generated by Django 4.2.8 on 2026-01-01 12:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("samples", "0003_add_sample_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplerun",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="materials_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="production_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="quoted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="snapshotted_at",
            field=models.DateTimeField(
                blank=True, help_text="When BOM/Operations were snapshotted", null=True
            ),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="source_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA256 hash of snapshotted BOM + Operations",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="source_revision_id",
            field=models.UUIDField(
                blank=True, help_text="Source revision ID at snapshot time", null=True
            ),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="source_revision_label",
            field=models.CharField(
                blank=True,
                help_text="Source revision label (e.g., 'Rev A')",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RunOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_no", models.IntegerField(help_text="Step number")),
                ("step_name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("machine_type", models.CharField(blank=True, max_length=100)),
                (
                    "std_minutes",
                    models.IntegerField(default=0, help_text="Standard minutes"),
                ),
                ("special_requirements", models.TextField(blank=True)),
                (
                    "source_construction_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Original ConstructionStep ID for reference",
                        null=True,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="samples.samplerun",
                    ),
                ),
            ],
            options={
                "db_table": "run_operations",
                "ordering": ["step_no"],
                "indexes": [
                    models.Index(fields=["run"], name="run_operati_run_id_5534fc_idx")
                ],
                "unique_together": {("run", "step_no")},
            },
        ),
        migrations.CreateModel(
            name="RunBOMLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "line_no",
                    models.IntegerField(help_text="Line number in BOM snapshot"),
                ),
                ("material_name", models.CharField(max_length=200)),
                ("material_name_zh", models.CharField(blank=True, max_length=200)),
                ("material_code", models.CharField(blank=True, max_length=80)),
                ("category", models.CharField(blank=True, max_length=60)),
                ("color", models.CharField(blank=True, max_length=80)),
                ("uom", models.CharField(help_text="Unit of measure", max_length=16)),
                (
                    "consumption",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Consumption per garment",
                        max_digits=12,
                    ),
                ),
                (
                    "wastage_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Wastage percentage",
                        max_digits=6,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("supplier_name", models.CharField(blank=True, max_length=120)),
                ("supplier_id", models.UUIDField(blank=True, null=True)),
                ("leadtime_days", models.IntegerField(default=0)),
                (
                    "source_bom_item_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Original BOMItem ID for reference",
                        null=True,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_lines",
                        to="samples.samplerun",
                    ),
                ),
            ],
            options={
                "db_table": "run_bom_lines",
                "ordering": ["line_no"],
                "indexes": [
                    models.Index(fields=["run"], name="run_bom_lin_run_id_a98297_idx"),
                    models.Index(
                        fields=["material_name"], name="run_bom_lin_materia_51e8e8_idx"
                    ),
                ],
                "unique_together": {("run", "line_no")},
            },
        ),
    ]
