# Generated by Django 4.2.8 on 2026-01-02 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("samples", "0004_add_p0_1_snapshot_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplerequest",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization (tenant) this request belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sample_requests",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="samplerun",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization (tenant) this run belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sample_runs",
                to="core.organization",
            ),
        ),
    ]
