# Generated by Django 4.2.8 on 2026-01-02 12:41
# SaaS-Ready: Backfill organization FK for samples models

from django.db import migrations


def backfill_organization(apps, schema_editor):
    """
    Backfill organization FK from parent models:
    - SampleRequest: get organization from revision -> style
    - SampleRun: get organization from sample_request -> revision -> style
    """
    SampleRequest = apps.get_model('samples', 'SampleRequest')
    SampleRun = apps.get_model('samples', 'SampleRun')

    # Backfill SampleRequest
    for request in SampleRequest.objects.select_related('revision__style').iterator():
        if request.revision and request.revision.style and request.revision.style.organization_id:
            request.organization_id = request.revision.style.organization_id
            request.save(update_fields=['organization_id'])

    # Backfill SampleRun
    for run in SampleRun.objects.select_related('sample_request__revision__style').iterator():
        if (run.sample_request and run.sample_request.revision and
            run.sample_request.revision.style and run.sample_request.revision.style.organization_id):
            run.organization_id = run.sample_request.revision.style.organization_id
            run.save(update_fields=['organization_id'])


def reverse_backfill(apps, schema_editor):
    """Reverse: set all organization FKs back to NULL"""
    SampleRequest = apps.get_model('samples', 'SampleRequest')
    SampleRun = apps.get_model('samples', 'SampleRun')

    SampleRequest.objects.update(organization=None)
    SampleRun.objects.update(organization=None)


class Migration(migrations.Migration):
    dependencies = [
        ("samples", "0005_add_organization_fk"),
        # Ensure styles migration runs first (for Style.organization to exist)
        ("styles", "0008_backfill_organization"),
    ]

    operations = [
        migrations.RunPython(backfill_organization, reverse_backfill),
    ]
