# Generated by Django 4.2.8 on 2026-01-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samples", "0006_backfill_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplerun",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Version number for optimistic locking (incremented on each save)",
            ),
        ),
    ]
