# Generated by Django 4.2.8 on 2026-01-02 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_saas_ready_fields"),
        ("samples", "0007_saas_ready_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplecostestimate",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization (tenant) this estimate belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sample_cost_estimates",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="samplemwo",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization (tenant) this MWO belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sample_mwos",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="t2poforsample",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization (tenant) this T2PO belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="t2pos_for_sample",
                to="core.organization",
            ),
        ),
    ]
