# Generated by Django 4.2.8 on 2026-01-11 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("costing", "0007_alter_usagescenario_purpose"),
        ("samples", "0010_alter_runoperation_translation_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runoperation",
            name="description_zh",
            field=models.TextField(
                blank=True, help_text="Chinese translation of operation description"
            ),
        ),
        migrations.AlterField(
            model_name="runoperation",
            name="machine_type_zh",
            field=models.CharField(
                blank=True,
                help_text="Chinese translation of machine type",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="runoperation",
            name="stitch_type_zh",
            field=models.CharField(
                blank=True,
                help_text="Chinese translation of stitch type",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="samplerun",
            name="actual_usage",
            field=models.ForeignKey(
                blank=True,
                help_text="Actual usage recorded after sample done",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sample_runs_actual",
                to="costing.usagescenario",
            ),
        ),
        migrations.AlterField(
            model_name="samplerun",
            name="costing_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Generated costing version from actuals",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sample_runs",
                to="costing.costsheetversion",
            ),
        ),
        migrations.AlterField(
            model_name="samplerun",
            name="guidance_usage",
            field=models.ForeignKey(
                blank=True,
                help_text="Guidance usage scenario for materials planning",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sample_runs_guidance",
                to="costing.usagescenario",
            ),
        ),
    ]
