# Generated by Django 4.2.8 on 2026-01-17 02:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("samples", "0011_add_related_names_for_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunTechPackPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_number", models.IntegerField(help_text="頁碼")),
                ("width", models.IntegerField(help_text="頁面寬度")),
                ("height", models.IntegerField(help_text="頁面高度")),
                (
                    "source_page_id",
                    models.UUIDField(
                        blank=True, help_text="原始 RevisionPage ID", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="techpack_pages",
                        to="samples.samplerun",
                    ),
                ),
            ],
            options={
                "db_table": "run_techpack_pages",
                "ordering": ["page_number"],
            },
        ),
        migrations.CreateModel(
            name="RunTechPackBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("block_type", models.CharField(blank=True, max_length=30)),
                ("source_text", models.TextField(help_text="原文（英文）")),
                ("translated_text", models.TextField(help_text="翻譯（中文）")),
                ("bbox_x", models.FloatField(default=0)),
                ("bbox_y", models.FloatField(default=0)),
                ("bbox_width", models.FloatField(default=0)),
                ("bbox_height", models.FloatField(default=0)),
                (
                    "overlay_x",
                    models.FloatField(blank=True, help_text="翻譯文字框 X 位置", null=True),
                ),
                (
                    "overlay_y",
                    models.FloatField(blank=True, help_text="翻譯文字框 Y 位置", null=True),
                ),
                (
                    "overlay_visible",
                    models.BooleanField(default=True, help_text="是否顯示此翻譯"),
                ),
                (
                    "source_block_id",
                    models.UUIDField(
                        blank=True, help_text="原始 DraftBlock ID", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="samples.runtechpackpage",
                    ),
                ),
            ],
            options={
                "db_table": "run_techpack_blocks",
                "ordering": ["bbox_y", "bbox_x"],
            },
        ),
        migrations.AddIndex(
            model_name="runtechpackpage",
            index=models.Index(fields=["run"], name="run_techpac_run_id_0ce65a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="runtechpackpage",
            unique_together={("run", "page_number")},
        ),
        migrations.AddIndex(
            model_name="runtechpackblock",
            index=models.Index(
                fields=["run_page"], name="run_techpac_run_pag_d08e9c_idx"
            ),
        ),
    ]
