# Generated by Django 5.0.14 on 2026-02-09 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_status_timestamps(apps, schema_editor):
    """回填現有 SampleRun 的 status_timestamps"""
    SampleRun = apps.get_model('samples', 'SampleRun')
    for run in SampleRun.objects.all():
        timestamps = {}
        # draft 用 created_at
        if run.created_at:
            timestamps['draft'] = run.created_at.isoformat()
        # 當前狀態用 status_updated_at（如果不是 draft）
        if run.status != 'draft' and run.status_updated_at:
            timestamps[run.status] = run.status_updated_at.isoformat()
        if timestamps:
            run.status_timestamps = timestamps
            run.save(update_fields=['status_timestamps'])


class Migration(migrations.Migration):
    dependencies = [
        ("samples", "0012_add_overlay_and_techpack_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="samplerun",
            name="status_timestamps",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"draft": "2026-01-01T00:00:00Z", "materials_planning": "2026-01-02T...", ...}',
            ),
        ),
        migrations.AlterField(
            model_name="samplerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("quote_requested", "Quote Requested"),
                    ("quoted", "Quoted"),
                    ("approved", "Approved"),
                    ("in_execution", "In Execution"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("open", "Open"),
                    ("on_hold", "On Hold"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="SampleRunTransitionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(max_length=24)),
                ("to_status", models.CharField(max_length=24)),
                (
                    "action",
                    models.CharField(
                        help_text="Action name: submit, approve, rollback, cancel, etc.",
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transition_logs",
                        to="samples.samplerun",
                    ),
                ),
            ],
            options={
                "db_table": "sample_run_transition_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sample_run", "-created_at"],
                        name="sample_run__sample__aadbc7_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_status_timestamps, migrations.RunPython.noop),
    ]
